---

- name: "Install/Remove package unattended-upgrades"
  apt:
    update_cache: true
    name: "unattended-upgrades"
    state: "{{ autoupdate_enabled | ternary('present', 'absent') }}"

- name: "Deploy configs"
  ansible.builtin.template:
    src: "templates/{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "auto-upgrades.j2"
      dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    - src: "unattended-upgrades.j2"
      dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
  when: "autoupdate_enabled"

- name: "Restart service"
  ansible.builtin.systemd:
    name: "unattended-upgrades"
    state: "restarted"
  when: "autoupdate_enabled"

- name: "Remove configs"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "/etc/apt/apt.conf.d/20auto-upgrades"
    - "/etc/apt/apt.conf.d/50unattended-upgrades"
  when: "not autoupdate_enabled"
